{% set name = "julia" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/JuliaLang/julia.git
  git_tag: v{{ version }}

build:
  skip: True  # [win]
  number: 0
  features:

requirements:
  build:
    - perl
    - python 3.*
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openblas-ilp64
    - patchelf  # [linux]
    - openlibm 0.5.4
    - gmp
    - mpfr
    - curl
    - libgit2
    - libosxunwind  # [osx]
    - arpack
    - suitesparse
    - pcre2 10.36
    - git

  run:
    - openblas-ilp64
    - libosxunwind  # [osx]
    - gmp
    - mpfr
    - openlibm 0.5.4
    - arpack
    - suitesparse
    - pcre2 10.36
    - curl
    - libgit2
    - git

test:
  commands:
    - julia -e 'Base.runtests(["core","Downloads"])'
  requires:
    - perl

about:
  home: http://julialang.org/
  license: MIT
  license_file: LICENSE.md
  summary: A high-performance dynamic programming language for data science

extra:
  recipe-maintainers:
    - SylvainCorlay
    - bgruening
    - dfornika
    - acaprez
    - mariusvniekerk
    - abhi18av
