{% set name = "julia" %}
{% set version = "1.6.2" %}
{% set sha256 = "01241120515cb9435b96179cf301fbd2c24d4405f252588108d13ceac0f41c0a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: julia-{{ version }}-full.tar.gz
  url: https://github.com/JuliaLang/julia/releases/download/v{{ version }}/julia-{{ version }}-full.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 0
  features:

requirements:
  build:
    - perl
    - python 3
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openblas-ilp64
    - patchelf  # [linux]
    - openlibm
    - gmp
    - mpfr
    - libgit2  # [not osx]
    - libssh2
    - libosxunwind  # [osx]
    - libunwind  # [linux]
    - arpack
    - suitesparse
    - pcre2
    - git
    - libnghttp2
    - zlib
    - p7zip

  run:
    - openblas-ilp64
    - libosxunwind  # [osx]
    - libunwind  # [linux]
    - gmp
    - mpfr
    - openlibm
    - arpack
    - suitesparse
    - pcre2
    - libgit2  # [not osx]
    - libssh2
    - git
    - libnghttp2
    - zlib
    - p7zip

test:
  commands:
    - julia -e 'Base.runtests(["core", "regex", "Downloads"])'
  requires:
    - perl

about:
  home: http://julialang.org/
  license: MIT
  license_file: LICENSE.md
  summary: A high-performance dynamic programming language for data science

extra:
  recipe-maintainers:
    - SylvainCorlay
    - bgruening
    - dfornika
    - acaprez
    - mariusvniekerk
    - abhi18av
